### ISSUE TITLE
KeyCloak loop back when default Resources are defined

### ISSUE THREAD

**Issue by usamaahmadkhan** [stakater/StakaterPlatform#53]
Gives error on:
```
      resources:
        limits:
          cpu: 200m
          memory: 4096Mi
        requests:
           cpu: 100m
           memory: 2048Mi
```
Works fine when:
```
       resources: {}
```
